### ISSUE TITLE
About separate of concerns to make the components easy to reason about

### ISSUE THREAD

**Issue by joaolavoier-luizalabs** [diegohaz/singel#15]
Hi, great job! 

I've loved this library and the Singel's concepts, that's really awesome. But there is a concept that I think should be dangerous, like the obligation to pass the `style` and `classNames` props up to the parent component.

I think this concept so much rigorous to make your application not scalable. I think it make sense in some cases, but not at all. Sometimes I need to encapsulate the styles of a component and control it by a prop as the article is against. 

When you are thinking about the **responsibility** of the components. When you would like to create the **styled** components with the characteristics of your application, and you want to give this responsibility just to the **styled components**, so the styles will be just into the **styled component**. 

### The benefits 

- It keeps you application clear, because you wont use styles in whole application.
- When you need to change the style or a behaviour, you will just change a single component.
- It fits as a glove about [separating presentational and container components](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0)

## Resume 
In my opinion, it would be a bad approach.

``` js
// good
const Element = ({ className, ...props }) => (
  <div className={`foo ${className}`} {...props} />
);

// good
const Element = ({ style, ...props }) => (
  <div style={{ padding: 0, ...style }} {...props} />
);
```

Therefore you are allowing this:

``` js
const WrapperContainerComponent = ({ isChecked }) => (
  <Element style={{ padding: 0, backgroundColor: isChecked ? "blue" : "white" }}  />
);
```

Instead of this:

``` js
// Wrapper
const WrapperContainerComponent = ({ isChecked }) => (
  <Element isChecked={isChecked}  />
);
```

``` js
//Styled component
const Element = ({ isChecked }) => (
  <div style={getStyles(isChecked)}  />
);

const getStyles = (isChecked) => ({
  padding: 0,
  backgroundColor: isChecked ? "blue" : "white"
})
```

**Comment by diegohaz** [comment]
Hi, @joaolavoier-luizalabs. Thank you very much for your feedback.

I think Singel has nothing to do with the separation of presentational and container components. This actually proposes a separation between presentational components and primitives. This is a pattern for the most abstract level of your component tree.

Your primitives should be flexible enough for your application to scale. This means that when your designer comes up with a new kind of button, for instance, you should be able to easily implement that taking advantage of the current primitives, when possible, and without worrying about breaking other parts of the application.

If you encapsulate your style inside your primitive and make it not extensible, whenever you add a new variant you'll have to update that component. 

If you ever scaled an app to a point that several components are depending on another one, which has a bunch of custom props controlling different styles, you know that updating it has a high chance to break something else. Singel just lowers those chances.

That's fine (and actually unavoidable) to have other presentational components that don't follow Singel. I usually create an [`elements` folder](https://github.com/diegohaz/reas/tree/reakit/website/src/elements) with single elements and a [`components` folder](https://github.com/diegohaz/reas/tree/reakit/website/src/components) with all the other presentational components. I only abstract new single elements from components when I can understand the correct abstraction. This may take time and is usually done in refactors, over time.

That's only my point of view, of course. This discussion is really valuable.

**Comment by joaolavoier-luizalabs** [comment]
Hi @diegohaz. A really appreciate your fast answer, thanks! :)

Please let me know if I didn't understand correctly. 

```
Container Components
        /|\
         |
Presentational Components
        /|\
         |  <----- Are you talking about this?
         |
Primitive Elements
```

And it doesn't care about how the presentational components has to be, and the presentational components can has its style encapsulated. It would be about a more generic abstraction, when you want to create a UI library to distribute. Yes, so I agree. 

I usually like to create my own UI components with the presentational components, so in order to I use this concepts, will I need to create a most abstract new level of components and use it to create my presentational UI?

**Comment by diegohaz** [comment]
Yes, you got it. 

Those guidelines really shines on UI libraries. But, in a smaller proportion, every project has its own UI library underneath.

As an example, I was working on a private project with some separate apps, like `www`, `admin` and `medical`. Even though they were being bundled separately, they shared the same UI primitives, with sensible default styles, but flexible enough to accommodate design differences between the apps.

Each app, in turn, had its own small UI library, extending the shared one and applying more specific styles when needed. Being able to also pass new `className` and `style` to them was really convenient to, among other things, tweak their style based on a context (a `page`, for example).

**Comment by jmlavoier** [comment]
Now I guess I got it. I will study and try to aply this on my own projects.
