### ISSUE TITLE
Cannot find module 'prop-types'

### ISSUE THREAD

**Issue by mbarzeev** [diegohaz/singel#26]
Hi,

When I try and run the tool with the most basic form, I'm getting the following error:
`Error: Cannot find module 'prop-types'`
Also the --ignore doesn't seem to be taken into account.
What am I missing?

Thanks :)

**Comment by diegohaz** [comment]
Could you paste here the command you're using? (with --ignore)

> `Error: Cannot find module 'prop-types'`
Is this the whole output?

Did you `npm install` the project's dependencies, right?

**Comment by mbarzeev** [comment]
Thanks for the quick response.
The project configuration is a bit non-conventional. I sorted it out. All seem to be ok now :)
Closing.
